# Generated by Django 5.2.8 on 2025-11-06 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('contacto', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id_videojuego', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('genero', models.CharField(max_length=100)),
                ('plataforma', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_lanzamiento', models.DateField()),
                ('desarrollador', models.CharField(max_length=150)),
                ('id_proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videojuegos', to='app_Xbox.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('cliente_nombre', models.CharField(max_length=255)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_videojuego', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='app_Xbox.videojuego')),
            ],
        ),
    ]
